### ISSUE TITLE
Error When Setting Up Connection To Server

### ISSUE THREAD

**Issue by yiruzu** [Tuncion/vscode-fivem-resource-manager#5]
![image](https://github.com/Tuncion/vscode-fivem-resource-manager/assets/94981325/6dbf5907-2493-41b2-a495-407817893b8a)

**Comment by Tuncion** [comment]
@yiruzu need more information, your screenshot is not exclusionary. Does the screenshot come directly from VSC? Never seen this error in this notify style.

**Comment by 5xrp** [comment]
connect ECONNREFUSED 127.0.0.1:30120

**Comment by yiruzu** [comment]
I got the error after i tried to connect to my server and yes the notification comes from VSC.

**Comment by Tuncion** [comment]
@yiruzu Can you tell me what you exactly entered in the IP:Port field? (To reproduce)

**Comment by yiruzu** [comment]
@Tuncion I entered the IPV4 adress from my server and the port "22".

**Comment by Tuncion** [comment]
Port 22 is the SSH port, enter the fxserver port (default is 30120)
It is set in your server CFG.

![image](https://github.com/Tuncion/vscode-fivem-resource-manager/assets/58955610/8bf0b492-7ac5-464b-9ea1-d55a7546cdf8)

`0.0.0.0` means anyhost here
`30120` the number after the `:` is your server port

---

You need to enter in the IP:Port field something like this: YOURIP:30120 (default)

**Comment by yiruzu** [comment]
Yeah, it works now thank you, I didn't really know which port the connection would need, so I just entered the SSH port in.
