### ISSUE TITLE
Can't install... Not compatible

### ISSUE THREAD

**Issue by zakso7961** [Tuncion/vscode-fivem-resource-manager#9]
![cantInstall](https://github.com/Tuncion/vscode-fivem-resource-manager/assets/49880415/85fd2e18-9037-465b-8d13-f13eb9275294)

Can't install 'vioritygroup.fivem-resource-manager' extension because it is not compatible with the current version of Code - OSS (version 1.63.2).

**Comment by Tuncion** [comment]
Hello,

please update your VS Code. The requirement is version 1.82.0 or higher. You have version 1.63.2, the latest version is currently 1.85 (November 2023) see https://code.visualstudio.com/updates/v1_85
